// Generated by gencpp from file marine_sensor_msgs/RadarEcho.msg
// DO NOT EDIT!


#ifndef MARINE_SENSOR_MSGS_MESSAGE_RADARECHO_H
#define MARINE_SENSOR_MSGS_MESSAGE_RADARECHO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marine_sensor_msgs
{
template <class ContainerAllocator>
struct RadarEcho_
{
  typedef RadarEcho_<ContainerAllocator> Type;

  RadarEcho_()
    : echoes()  {
    }
  RadarEcho_(const ContainerAllocator& _alloc)
    : echoes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _echoes_type;
  _echoes_type echoes;





  typedef boost::shared_ptr< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> const> ConstPtr;

}; // struct RadarEcho_

typedef ::marine_sensor_msgs::RadarEcho_<std::allocator<void> > RadarEcho;

typedef boost::shared_ptr< ::marine_sensor_msgs::RadarEcho > RadarEchoPtr;
typedef boost::shared_ptr< ::marine_sensor_msgs::RadarEcho const> RadarEchoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marine_sensor_msgs::RadarEcho_<ContainerAllocator1> & lhs, const ::marine_sensor_msgs::RadarEcho_<ContainerAllocator2> & rhs)
{
  return lhs.echoes == rhs.echoes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marine_sensor_msgs::RadarEcho_<ContainerAllocator1> & lhs, const ::marine_sensor_msgs::RadarEcho_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marine_sensor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8bc5ae449b200fba4d552b4225586696";
  }

  static const char* value(const ::marine_sensor_msgs::RadarEcho_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8bc5ae449b200fbaULL;
  static const uint64_t static_value2 = 0x4d552b4225586696ULL;
};

template<class ContainerAllocator>
struct DataType< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marine_sensor_msgs/RadarEcho";
  }

  static const char* value(const ::marine_sensor_msgs::RadarEcho_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message is a submessage of RadarSector and is not intended\n"
"# to be used separately. It represents intensities from a\n"
"# single ray.\n"
"\n"
"# Series of intensities from closest to farthest\n"
"# along a given angle increment. [device-specific units]\n"
"float32[] echoes\n"
;
  }

  static const char* value(const ::marine_sensor_msgs::RadarEcho_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.echoes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarEcho_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marine_sensor_msgs::RadarEcho_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marine_sensor_msgs::RadarEcho_<ContainerAllocator>& v)
  {
    s << indent << "echoes[]" << std::endl;
    for (size_t i = 0; i < v.echoes.size(); ++i)
    {
      s << indent << "  echoes[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.echoes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARINE_SENSOR_MSGS_MESSAGE_RADARECHO_H
